### ISSUE TITLE
Reason for running calico/node container on kubernetes master

### ISSUE THREAD

**Issue by AdoHe** [projectcalico/calico-kubernetes#112]
FYI. Why we have to run `calico/node` container on kubernetes master?

**Comment by caseydavenport** [comment]
@AdoHe - `calico/node` needs to run on the kubernetes master so that it knows how to route to pod IP addresses.

The typically example is the Kubernetes DNS addon - the pod needs to access the Kubernetes API running on the master, and so the master must be able to route packets back to the pod.
