### ISSUE TITLE
Get master in node-to-node-mesh

### ISSUE THREAD

**Issue by mzupan** [projectcalico/calico-kubernetes#126]
I'm trying to get autoscaling working with calico as my network layer and its not working in AWS. 

horizontal autoscaling needs heapster running in the kube-system namespace. Heapster needs to hit the kublet port (10255) on every k8 node. 

The issue I'm having is when I run heapster in kubernetes I'm able to connect to the port just fine but the kubernetes controller needs to connect to heapster via the api proxy and that is running on the master and it times out because the master node cannot reach the calico /16 vlan. 

If i add the following route rules on master/nodes

```
ip rule add from 192.168.0.0/16 table docker
ip route add 10.122.41.0/24 table docker dev tunl0
ip route add 10.122.42.0/24 table docker dev tunl0
ip route add 10.122.43.0/24 table docker dev tunl0
```

That is able to work but the heapster->kublet port breaks. 

I'm in sort of a catch 22 because I can run heapster in docker on the master but connections aren't getting returned.. I see the ping but then its lost. 

```
[root@kube-node_e5aa5956 ~] [dev] # tcpdump -v icmp -i any
tcpdump: listening on any, link-type LINUX_SLL (Linux cooked), capture size 65535 bytes
14:10:05.285965 IP (tos 0x0, ttl 63, id 24290, offset 0, flags [DF], proto ICMP (1), length 84)
    ip-10-122-0-20.ec2.internal > ip-10-122-43-138.ec2.internal: ICMP echo request, id 7680, seq 14, length 64
14:10:06.286078 IP (tos 0x0, ttl 63, id 24291, offset 0, flags [DF], proto ICMP (1), length 84)
    ip-10-122-0-20.ec2.internal > ip-10-122-43-138.ec2.internal: ICMP echo request, id 7680, seq 15, length 64
14:10:07.288024 IP (tos 0x0, ttl 63, id 24292, offset 0, flags [DF], proto ICMP (1), length 84)
    ip-10-122-0-20.ec2.internal > ip-10-122-43-138.ec2.internal: ICMP echo request, id 7680, seq 16, length 64
14:10:08.288130 IP (tos 0x0, ttl 63, id 24293, offset 0, flags [DF], proto ICMP (1), length 84)
    ip-10-122-0-20.ec2.internal > ip-10-122-43-138.ec2.internal: ICMP echo request, id 7680, seq 17, length 64
14:10:09.291316 IP (tos 0x0, ttl 63, id 24294, offset 0, flags [DF], proto ICMP (1), length 84)
    ip-10-122-0-20.ec2.internal > ip-10-122-43-138.ec2.internal: ICMP echo request, id 7680, seq 18, length 64
14:10:10.292318 IP (tos 0x0, ttl 63, id 24295, offset 0, flags [DF], proto ICMP (1), length 84)
    ip-10-122-0-20.ec2.internal > ip-10-122-43-138.ec2.internal: ICMP echo request, id 7680, seq 19, length 64
^C
```

I never see the return.

10.122.0.20 is my master

My status is as follows

```
[root@kube-master ~] [dev] # calicoctl status
calico-node container is running. Status: Up 21 hours
Running felix version 1.3.0rc5

IPv4 BGP status
+---------------+-------------------+-------+------------+-------------+
|  Peer address |     Peer type     | State |   Since    |     Info    |
+---------------+-------------------+-------+------------+-------------+
| 10.122.42.163 | node-to-node mesh |   up  | 2015-12-23 | Established |
| 10.122.43.138 | node-to-node mesh |   up  | 2015-12-23 | Established |
+---------------+-------------------+-------+------------+-------------+

IPv6 BGP status
+--------------+-----------+-------+-------+------+
| Peer address | Peer type | State | Since | Info |
+--------------+-----------+-------+-------+------+
+--------------+-----------+-------+-------+------+

```

Those are my two k8 nodes.. I'm able to ping from container->container just fine if the container is running on a k8 node. If a container is running on the master it doesn't work

EDIT

route table for a node

```
[root@kube-node_123d65a4 ~] [dev] # ip route
default via 10.122.42.1 dev eth0
10.122.42.0/24 dev eth0  proto kernel  scope link  src 10.122.42.163
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.42.1
192.168.0.0 dev cali9cc2065aa99  scope link
blackhole 192.168.0.0/26  proto bird
192.168.0.1 dev cali9cf4e624a99  scope link
192.168.0.2 dev cali0f5e619aa99  scope link
192.168.0.3 dev cali47ded9a4a9b  scope link
192.168.0.64/26 via 10.122.43.138 dev tunl0  proto bird onlink
192.168.0.128/26 via 10.122.0.20 dev tunl0  proto bird onlink
```

Route table for master

```
[root@kube-master ~] [dev] # ip route
default via 10.122.0.1 dev eth0
10.122.0.0/24 dev eth0  proto kernel  scope link  src 10.122.0.20
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.42.1
192.168.0.0/26 via 10.122.42.163 dev tunl0  proto bird onlink
192.168.0.64/26 via 10.122.43.138 dev tunl0  proto bird onlink
blackhole 192.168.0.128/26  proto bird
```

**Comment by caseydavenport** [comment]
@mzupan - sorry for the delay, not sure how I missed this issue.

> I'm able to ping from container->container just fine if the container is running on a k8 node. If a container is running on the master it doesn't work
The containers running on the master, are they created via Kubernetes?  If so, have you installed the Calico plugin on the master?  If they're just running through Docker, you'll need to add them to Calico explicitly or else Calico won't know how to route to them.  I don't see any local container routes in your master's routing table, so my best guess is that the containers on your master haven't been added to Calico.

> running on the master and it times out because the master node cannot reach the calico /16
Yes, this sounds like the ipip on-ramp issue, since adding those routes fixed it.

> That is able to work but the heapster->kublet port breaks.
I think this is an interference with the behavior of the `ipip` workaround and the `--nat-outgoing` option.  The `--nat-outgoing` option will break pod->node traffic when the `ipip` workaround routes are in place.  However, without `--nat-outgoing`, you won't be able to do pod->external traffic.  

We're working on a better public cloud solution for Calico + Kubernetes at the moment and should hopefully have a better option to support both ipip and nat-outgoing soon - likely this month.

**Comment by caseydavenport** [comment]
@mzupan - This should be fixed up by using calicoctl and calico/node version 0.14.0.  Please give that a try when you have a chance and let us know if it fixes your problem.  You shouldn't need the workaround routes described above with this release.

**Comment by mzupan** [comment]
works great since 0.14.0!
