### ISSUE TITLE
Support different types of authentication.

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico-kubernetes#14]
Support the various types of authentication for plugins as described here.

https://github.com/kubernetes/kubernetes/blob/master/docs/admin/authentication.md

**Comment by Symmetric** [comment]
Initial design thinking: I don't think we need to support all of these auth methods; as long as we have one easy-to-configure way of granting Calico access.

My current plan is to implement bearer token support (probably replacing basic auth), and include instructions for either using Kubelet's token (if that's what kubelet is using), or generating a read-only ServiceAccount token for Calico.
