### ISSUE TITLE
Plugin logs should include process ID

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico-kubernetes#26]
The Kubelet might call multiple instances of the plugin at the same time.  All logs are written to the same file, which makes correlating logs to plugin instances confusing.  The logs should at least have the process ID so we can follow a single instance of the plugin.

**Comment by caseydavenport** [comment]
@L-MA - Can you confirm if this is fixed in master, and close this issue if it is?

**Comment by L-MA** [comment]
Supported in PR #23
