### ISSUE TITLE
Proper way to expose a service

### ISSUE THREAD

**Issue by Smana** [projectcalico/calico-kubernetes#31]
Hello,

I have a private cluster so i use the "NodePort" service type.

With flannel i would have used an external load balancer to spread the load over my nodes but maybe there'a better way with calico ? (ecmp ...)

Regards,
Smana

**Comment by Smana** [comment]
note: my nodes are peering with the edge routers

**Comment by caseydavenport** [comment]
Hi Smana,

For now, an external load balancer and NodePort is probably still the way to go in terms of exposing services to the outside world.

Calico currently doesn't know about Kubernetes service clusterIPs (VIPs).  Ultimately, it would be great if we could do away with NodePort altogether and make the load balancer aware of services / pods so it could perform ECMP to service-backing pods directly.

cc @Symmetric - anything to add?

**Comment by Smana** [comment]
Ok thank you, so i'll request the API in order to generate my Haproxy configuration.
