### ISSUE TITLE
Understanding Networking

### ISSUE THREAD

**Issue by Smana** [projectcalico/calico-kubernetes#33]
Hello,

Sorry to bother you again but i'd like to have more information on how is configured a pod's networking.
I already have a kubernetes cluster working with calico and deployed with Ansible.

* I've understand that every container has an ip from a calico pool (stored in etcd), and there's a specific route for each pod. These ip are distributed with bgp (bird) to all the nodes.

* But more precisely, what happens when i create a pod ?

* What is the process in charge of creating the interface calixxxxx ?

* What kind of interface is it ? i expected it to be a veth.
But from my understanding a veth comes in pairs one attached to the default namespace and another one in the container namespace. But there's only one network namespace.
```
ip netns list
```

* What is excatly the purpose of the bridge cbr0 ?
```
bridge name	bridge id		STP enabled	interfaces
cbr0		8000.000000000000	no
```

* How is configured the networking inside the pod ?

* I've notice that every interface calixxx has the same ip
```
5: cbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet 10.233.1.1/24 scope global cbr0
       valid_lft forever preferred_lft forever
    inet6 fe80::10eb:6ff:fedf:9583/64 scope link 
       valid_lft forever preferred_lft forever
9: calic5d012a84ff: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 26:fc:40:73:c9:9c brd ff:ff:ff:ff:ff:ff
    inet 10.115.77.87/32 scope global calic5d012a84ff
       valid_lft forever preferred_lft forever
    inet6 fe80::24fc:40ff:fe73:c99c/64 scope link 
       valid_lft forever preferred_lft forever
15: califb85ed004ff: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 7a:bd:cc:6d:d3:f3 brd ff:ff:ff:ff:ff:ff
    inet 10.115.77.87/32 scope global califb85ed004ff
       valid_lft forever preferred_lft forever
    inet6 fe80::78bd:ccff:fe6d:d3f3/64 scope link 
```

It is the gateway for the other nodes to reach the pods.
```
kubenode-2 ~ 0 # ip r
default via 10.115.255.253 dev eth0 
10.0.0.0/8 via 10.115.255.254 dev eth0 
10.115.0.0/16 dev eth0  proto kernel  scope link  src 10.115.77.88 
10.233.0.0/24 via 10.115.77.86 dev eth0  proto bird 
10.233.1.0/24 via 10.115.77.87 dev eth0  proto bird 
10.233.1.2 via 10.115.77.87 dev eth0  proto bird 
10.233.1.3 via 10.115.77.87 dev eth0  proto bird 
10.233.1.4 via 10.115.77.87 dev eth0  proto bird 
10.233.1.5 via 10.115.77.87 dev eth0  proto bird 
```
So i guess that when a packet arrive it is passed to the right interface based on mac address ? right ?

* How are the packets forwarded to the pod ?

Thank you,
Smana

**Comment by Smana** [comment]
Furthermore, i've just done the test of rebooting my host and all the network interfaces disapeared :(
Calico still seems to be configured as previously 
```
calicoctl profile show
+------------------------------------+
|                Name                |
+------------------------------------+
|              busybox               |
|   elasticsearch_logging_v1_1jzvs   |
|   elasticsearch_logging_v1_az6c8   |
| fluentd_elasticsearch_10.115.77.87 |
| fluentd_elasticsearch_10.115.77.88 |
| fluentd_elasticsearch_10.115.77.89 |
|      kibana_logging_v1_ifztn       |
|         kube_dns_v8_l6rtn          |
|         kube_dns_v8_tq8xf          |
|          kube_ui_v1_ym5ni          |
|    monitoring_heapster_v8_9cy06    |
|    monitoring_heapster_v8_pt4ey    |
| monitoring_influx_grafana_v1_obu8h |
+------------------------------------+
```
But there'is no calixxxx interface on the host anymore.
The pods on this host are unreachable

The docker daemon is still configured on cbr0
```
/usr/bin/docker -d -H fd:// --bridge=cbr0 --iptables=false --ip-masq=false
```
Maybe i forgot something ?

**Comment by caseydavenport** [comment]
Hi Smana, 

I'm opening another issue to track your host reboot issue - #34

**Comment by caseydavenport** [comment]
>But more precisely, what happens when i create a pod?


>What is the process in charge of creating the interface calixxxxx ?

We have a Calico plugin installed at `/usr/libexec/kubernetes/kubelet-plugins/net/exec/calico/calico` which is notified by the Kubelet whenever a pod is created or destroyed.  This plugin is responsible for setting up the calixxxx interface for the pod, and informing the per-node agent (calico/node) of the new endpoint.  This plugin also creates the security profile for the pod.

>What kind of interface is it ? i expected it to be a veth.

Yep, the calixxxxx interfaces are veths with one end in the host namespace, and one end in the pod's namespace.

>But from my understanding a veth comes in pairs one attached to the default namespace and another one in the container namespace. But there's only one network namespace.

Your understanding here is correct.  Off the top of my head, I'm not sure why they don't show up in `ip netns list` - @Symmetric any idea here?

>What is excatly the purpose of the bridge cbr0 ?

cbr0 is the Docker bridge.  In the current version of the Calico plugin, we use Docker's IPAM to assign pod IPs (docker selects an IP from the range specified on cbr0).  In the default docker model, cbr0 is used to switch traffic to the correct containers.  However, Calico removes the veths attached to cbr0 and creates calixxxxx interfaces which are routed instead.  So, when using Calico, cbr0 isn't a part of the network path for container traffic - its simply used for IPAM.  #23 is an open PR which removes the dependency on cbr0 for IPAM.

> How is configured the networking inside the pod ?

The pod simply has a default route to the host - nothing special going on here.  You can see this for yourself by running "ip route" inside the pod's namespace, like so:
```
cd4@cd4-kubernetes-master:~$ kubectl exec busybox -- ip route
default via 172.24.114.119 dev eth0
172.24.114.119 dev eth0  scope link
```

>I've notice that every interface calixxx has the same ip

Each calixxx interface has the same IP assigned on the host namespace side.  This is required for some of the REDIRECT iptables rules that some versions of the kube-proxy install.  This IP isn't used for routing traffic to or from the containers attached to the calixxx interfaces.  What really matters is the IP attached to the container side of the veth  - this is the actual IP address used to access the container.
```
kubectl exec busybox -- ifconfig eth0
eth0      Link encap:Ethernet  HWaddr 12:25:67:76:85:7F
          inet addr:192.168.1.27  Bcast:0.0.0.0  Mask:255.255.255.255
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:7 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:738 (738.0 B)  TX bytes:648 (648.0 B)
```

>So i guess that when a packet arrive it is passed to the right interface based on mac address ? right ?

Nope - Calico programs the linux forwarding table to direct traffic to the correct container via IP address.  You can see this by looking at the routing table on your various nodes.  Local containers will be accessible using routes that look like this:
```
# IP address 192.168.1.22 is accessible via the interface cali8dda216a526
192.168.1.22 dev cali8dda216a526  scope link
```

Containers on remote hosts will be accessible via routes learned over BGP, these look like the routes you pasted above.
```
# 10.233.1.4 is on remote host 10.155.77.87 - this was learned via BIRD (our BGP client)
10.233.1.4 via 10.115.77.87 dev eth0  proto bird 
```

* How are the packets forwarded to the pod ?

Packets are forwarded using the IP routing rules I mentioned directly above.  Packets destined to remote containers hit the route learned via BIRD, and are sent off to the next hop (in the above case, 10.155.77.87).  When the packet arrives at the node which is hosting the destination container, it hits a local routing rule which direct the packet through the calixxxx veth interface into the pod's namespace.

**Comment by Smana** [comment]
@caseydavenport, Thank you very much for this explanation. It is pretty clear :)

Last question: what about the performance compared to a physical nic? (throughput, latency)

I'll do some benchmarks asap anyway.

Regards

**Comment by Symmetric** [comment]
>> But from my understanding a veth comes in pairs one attached to the default namespace and another one in the container namespace. But there's only one network namespace.

>Your understanding here is correct. Off the top of my head, I'm not sure why they don't show up in ip netns list - @Symmetric any idea here?

Only named namespaces are shown by `ip netns list`. These are namespace fds that are created (or more commonly linked to) in `/var/run/netns/`.

All of the namespaces we create are in `/proc/<pid>/ns/net`, i.e. unnamed namespaces.

**Comment by caseydavenport** [comment]
@Smana - We've actually just recently posted on our blog about some of our dataplane performance testing.  It talks about metrics such as CPU usage, throughput, and latency.  You can find it here: http://www.projectcalico.org/calico-dataplane-performance/

**Comment by Smana** [comment]
Perfect :)
Thank you
