### ISSUE TITLE
Run calicoctl --kubernetes without internet

### ISSUE THREAD

**Issue by Smana** [projectcalico/calico-kubernetes#35]
Hello,

I'm currently doing tests with 2 nodes located on 2 different datacenters.
The problem is that my nodes can't access to the Internet.

I tried to run calicoctl but it didn't work with the following command : 
```
ETCD_AUTHORITY=10.17.252.11:4001 /usr/local/bin/calicoctl node --ip=10.17.252.27 --kubernetes
Override the host:port of the ETCD server by setting the environment variable
ETCD_AUTHORITY [default: 127.0.0.1:4001]

Usage: calicoctl <command> [<args>...]

    status            Print current status information
    node              Configure the main calico/node container and establish Calico networking
    container         Configure containers and their addresses
    profile           Configure endpoint profiles
    endpoint          Configure the endpoints assigned to existing containers
    pool              Configure ip-pools
    bgp               Configure global bgp
    checksystem       Check for incompatabilities on the host system
    diags             Save diagnostic information

See 'calicoctl <command> --help' to read about a specific subcommand.
```

I don't understand what's happening and there is no debug mode to figure it out.

Note:
* when i execute the same command without the --kubernetes option it works.
I guess it is related to the internet not reachable, is it ?
* I've copied the plugin from another server here : 
```
ls -ltr /usr/libexec/kubernetes/kubelet-plugins/net/exec/calico/calico
-rwxr-xr-x 1 root root 0 2015-09-08 08:06 /usr/libexec/kubernetes/kubelet-plugins/net/exec/calico/calico
```
* And i've imported the docker image
```
docker images 
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
calico/node         v0.5.1              ef4aab54c2ce        7 weeks ago         261.5 MB
```

Could you please help me to understand ?

Regards,
Smana

**Comment by TrimBiggs** [comment]
Hi @Smana,

I think the problem you are having with running `calicoctl node --kubernetes` is that the `--kubernetes` flag was not introduced in calicoctl until `v0.5.3`.  It looks like the calico/node docker image you are using is `v0.5.1` from 7 weeks ago, so your calicoctl binary might be old as well.  The calicoctl command will print the usage statement if it doesn't recognize the all of the parameters passed in.

The calico-docker repository builds the calicoctl binary and the calico/node docker image.  I recommend visiting the [calico-docker release page](https://github.com/projectcalico/calico-docker/releases) and downloading a newer version of calicoctl (`v0.6.0` is most recent).  

I'd also recommend pulling a newer version of calico/node by running:
```
docker pull calico/node:<version>
```
Replace  `<version>` with the calicoctl release version you chose (ex. `docker pull calico/node:v0.6.0`).  Alternatively, you could replace `<version>` with `latest` to pull the most recently built calico/node image based on the master branch of the calico-docker repo.

Let me know if this helps!

**Comment by caseydavenport** [comment]
It should also be noted that the `--kubernetes` flag will require outgoing internet connectivity, since it downloads the appropriate calico-kubernetes release.

If the nodes in your cluster don't have internet connectivity, you can manually download and install the plugin binary from the releases page and run `calicoctl node` without the `--kubernetes` flag.

**Comment by Smana** [comment]
Ok i'll copy the plugin from another server and i won't use the {code}--kubernetes{code} option
Thank you
