### ISSUE TITLE
How to run containers through Docker

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico-kubernetes#49]
From issue #34 @Smana 

>Now that the docker bridge is configured on a distinct network (172.16.0.0), i can't run docker containers for network debugging purpose. Indeed the pods are configured in the subnet 10.233.64.0/18.
Do you have a way to run a container into the calico pool network ?

**Comment by Symmetric** [comment]
The simplest option would be to use the kubectl container commands: `kubectl run` and `kubectl exec`. These map on to the equivalent docker commands. They don't support all of the docker arguments, but critically they do support forwarding an interactive tty (`-i -tty` flags on the kubectl commands). Any containers started through kubectl will get Calico networking via the kube network plugin.

**Comment by caseydavenport** [comment]
The downside with using `kubectl` is that you can't specify the node on which you want your container to run.  If you have a 10 node cluster and want to diagnose a specific node, that will be pretty tricky to do just using `kubectl`.

To my knowledge, you should still be able to create containers using `docker run`, but you will need to manually add them to Calico in order to get networking.  You can do this using the `calicoctl` tool with the following command:
```
calicoctl container add <CONTAINER> <IP>
```

The guide here shows an example of adding docker containers to Calico networking and configuring security profiles using `calicoctl` - https://github.com/projectcalico/calico-docker/blob/v0.7.0/docs/getting-started/default-networking/Demonstration.md#adding-calico-networking

**Comment by Smana** [comment]
Ok i'm going to test that asap, thank you :)

**Comment by Smana** [comment]
Hello @caseydavenport @Symmetric,
I've finally a first version of my ansible script : https://github.com/Smana/kubernetes-ansible

By the way this ticket can be closed, the ```-ti``` options of kubectl are exactly what i needed.
Thank you :)

Regards,
