### ISSUE TITLE
kube-proxy doesn't open ports

### ISSUE THREAD

**Issue by mzupan** [projectcalico/calico-kubernetes#50]
I've been playing with kubernetes in AWS and when I create a new service with a nodeport this version of kube-proxy

```
https://github.com/projectcalico/calico-kubernetes/releases/download/v0.1.1/kube-proxy
```

It never opens a port an sets the iptables rules on the host to send traffic to the proxy. 

All I see in the logs is

```
I0925 15:54:22.329156   31557 endpoints_tracker.go:115] EndpointsTracker: Setting endpoints for default/nginx: to [192.168.1.7:80 192.168.1.8:80 192.168.2.3:80 192.168.2.4:80]
```

In the proxy that comes with 1.0.3 I see something like

```
I0925 17:24:57.241261   14656 iptables.go:303] running iptables -A [KUBE-PORTALS-HOST -t nat -m comment --comment kube-system/kube-dns:dns -p udp -m udp --dport 53 -d 10.254.0.10/32 -j DNAT --to-destination 10.122.2.6:58129]
I0925 17:24:57.242735   14656 proxier.go:466] Opened iptables from-host portal for service "kube-system/kube-dns:dns" on UDP 10.254.0.10:53
I0925 17:24:57.242770   14656 proxier.go:326] Adding new service "kube-system/kube-dns:dns-tcp" at 10.254.0.10:53/TCP
I0925 17:24:57.242822   14656 proxier.go:268] Proxying for service "kube-system/kube-dns:dns-tcp" on TCP port 44191
```

From what I've been told this will be fixed with the 1.1 release but just making it known that I haven't found a way to use the `--legacy-userspace-proxy=false` to enable security in the proxy with 1.0.3-1.0.6

**Comment by caseydavenport** [comment]
I think this is a bug in our guides.  We specify a certain kube-proxy build to use which is not working with released versions of Kubernetes.  

@alexhersh will be taking a look at our guides.  @alexhersh - could you make sure you address this in your guides update?

**Comment by alexhersh** [comment]
In our [Policy doc](https://github.com/projectcalico/calico-docker/blob/master/docs/kubernetes/KubernetesPolicy.md) for kubernetes, we mention that [`kubernetes/kubernetes@b8dc963`](https://github.com/kubernetes/kubernetes/commit/b8dc963512326bcf7186026830b0dcbceecbcc80) is the appropriate commit for using the iptables proxy. However, shortly after this commit, a [PR](https://github.com/kubernetes/kubernetes/pull/12764) was merged into Kubernetes that fixed a few corner cases related to using NodePorts with iptables proxy. I will update our release to include a version of kube-proxy at this commit and update the docs to reference this PR.

**Comment by mzupan** [comment]
@alexhersh thanks!

**Comment by caseydavenport** [comment]
@alexhersh - I've merged the docs update, have you updated the binary?  If so, could you close this issue?

**Comment by alexhersh** [comment]
Sorry for the delay, @mzupan, I just got around to testing the new binaries. They are up on our [release page](https://github.com/projectcalico/calico-kubernetes/releases/tag/v0.2.0), and should fix your issue.

**Comment by mzupan** [comment]
@alexhersh thanks.. i take it they got pushed into the 0.2.0 release?

**Comment by alexhersh** [comment]
yes, as well as v0.1.0 and v0.1.1
