### ISSUE TITLE
access remote pod through calico from host on AWS

### ISSUE THREAD

**Issue by arjanschaaf** [projectcalico/calico-kubernetes#52]
Another follow-up question: I don't understand why I can't connect to a remote container using the following setup:

|'ve got a calico-kubernetes setup working using calicoctl 0.7.0 & kubernetes 1.1.0-alpha1!
I came to the conclusion that the setup is working because a created a replica controller with 2 replica's that both launched on different host machines and I can ping the remote container from the other container. Great succes! :-)

the kubelet configuration data:
```
ETCD_AUTHORITY=127.0.0.1:2379
CALICOCTL_PATH=/home/core/calicoctl
KUBE_API_ROOT=http://<k8-master>:8080/api/v1/
CALICO_IPAM=true
```

So I also use Calico IPAM, couldn't get this working on AWS with Docker IPAM.
AWS is relevant here: I don't have access to a full blown L2/L3 network so I configurered Calico to use an IPIP tunnel:

```
sudo ETCD_AUTHORITY=127.0.0.1:2379 ./calicoctl pool add 192.168.0.0/16 --ipip --nat-outgoing
```

**calicoctl endpoint show --detailed**
```
+--------------------------------------------+-----------------+------------------------------------------------------------------+----------------------------------+----------------+-------------------+---------------------------------------------+--------+
|                  Hostname                  | Orchestrator ID |                           Workload ID                            |           Endpoint ID            |   Addresses    |        MAC        |                   Profiles                  | State  |
+--------------------------------------------+-----------------+------------------------------------------------------------------+----------------------------------+----------------+-------------------+---------------------------------------------+--------+
| ip-10-150-32-32.eu-west-1.compute.internal |      docker     | 886094dd3e98126e52a5e2edac611aaec31eac08418b23f99723a6ebdaa4439b | 24b0137065e211e5a3ed06b84976d5a7 | 192.168.1.0/32 | fa:db:c6:ed:23:13 | default_todo-release-153-5w1wv_886094dd3e98 | active |
| ip-10-150-48-32.eu-west-1.compute.internal |      docker     | ca99437e7a49d22aa78735e2234676162672df11aad3318d37f26e6a9be3126b | 24a7a72665e211e591930abd28c5cad9 | 192.168.0.0/32 | 32:10:6f:99:74:d1 | default_todo-release-153-3qha2_ca99437e7a49 | active |
+--------------------------------------------+-----------------+------------------------------------------------------------------+----------------------------------+----------------+-------------------+---------------------------------------------+--------+
```

**calicoctl profile show --detailed**
```
+---------------------------------------------+--------------------------------------------+-----------------+------------------------------------------------------------------+----------------------------------+--------+
|                     Name                    |                    Host                    | Orchestrator ID |                           Workload ID                            |           Endpoint ID            | State  |
+---------------------------------------------+--------------------------------------------+-----------------+------------------------------------------------------------------+----------------------------------+--------+
| default_todo-release-153-3qha2_ca99437e7a49 | ip-10-150-48-32.eu-west-1.compute.internal |      docker     | ca99437e7a49d22aa78735e2234676162672df11aad3318d37f26e6a9be3126b | 24a7a72665e211e591930abd28c5cad9 | active |
| default_todo-release-153-5w1wv_886094dd3e98 | ip-10-150-32-32.eu-west-1.compute.internal |      docker     | 886094dd3e98126e52a5e2edac611aaec31eac08418b23f99723a6ebdaa4439b | 24b0137065e211e5a3ed06b84976d5a7 | active |
+---------------------------------------------+--------------------------------------------+-----------------+------------------------------------------------------------------+----------------------------------+--------+
```

**calicoctl profile default_todo-release-153-3qha2_ca99437e7a49 rule show**
```
Inbound rules:
   1 allow
Outbound rules:
   1 allow
```

**calicoctl profile default_todo-release-153-5w1wv_886094dd3e98 rule show**
```
Inbound rules:
   1 allow
Outbound rules:
   1 allow
```

**so who can connect to who?**
1. The containers launched by kubernetes *can* reach each other using the ip-addresses assigned by Calico
2. On host1 I *can* connect to the container running on host1 using the ip-address assigned by Calico
3. On host1 I *cannot* connect to the remote container on host2 using the ip-address assigned by Calico

Looking at the routing configuration on host1 I don't understand why I can't reach the remote container on host2:

```
default via 10.150.32.1 dev eth0  proto dhcp  src 10.150.32.32  metric 1024
10.150.32.0/20 dev eth0  proto kernel  scope link  src 10.150.32.32
10.150.32.1 dev eth0  proto dhcp  scope link  src 10.150.32.32  metric 1024
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.42.1
192.168.0.0 via 10.150.48.32 dev tunl0  proto bird onlink
192.168.1.0 dev cali24b0137065e  scope link
```

**Comment by caseydavenport** [comment]
@arjanschaaf - I think you're running in to this issue: https://github.com/projectcalico/calico-docker/issues/426.

I believe @Symmetric is currently investigating this.

**Comment by arjanschaaf** [comment]
@caseydavenport, @Symmetric that thread looks very similar. Although I have some difficulty to comprehend if the suggested workaround will apply to my setup and if so, how I need to configure it exactly

**Comment by Symmetric** [comment]
There's a lot of chatter on that issue, so here's the summary -- if you're on AWS, then you'll need this workaround to get traffic from a node to containers on another node:

```
# echo '8    docker' >> /etc/iproute2/rt_tables
# ip rule add from <cbr0 CIDR> table docker
# ip route add <nodes subnet> table docker dev tunl0
```

You may also need to disable RPF on your nodes:

`for if in all eth0 tunl0; do sudo bash -c "echo 0 > /proc/sys/net/ipv4/conf/${if}/rp_filter"; done`

Note that this latter RPF fix isn't suitable for production, since it reduces the security of the nodes. However the IP-in-IP feature is currently just intended for enabling developer trials in cloud environments; we're looking into ways of better supporting the ip-in-ip overlay mode.

Let me know if this works for you.

**Comment by Symmetric** [comment]
^Edited previous messge to clarify IP-in-IP status

**Comment by mzupan** [comment]
I'm pretty much having the same issue

my pool is set to 192.168.0.0/16
node1 = 192.168.1.1/24
node2 = 192.168.2.1/24

On node1 I ran

```
 echo '8    docker' >> /etc/iproute2/rt_tables
 ip rule add from 192.168.1.1/24 table docker
 ip route add 192.168.0.0/16 table docker dev tunl0
 for if in all eth0 tunl0; do sudo bash -c "echo 0 > /proc/sys/net/ipv4/conf/${if}/rp_filter"; done
```

on node2 i ran

```
 echo '8    docker' >> /etc/iproute2/rt_tables
 ip rule add from 192.168.2.1/24 table docker
 ip route add 192.168.0.0/16 table docker dev tunl0
 for if in all eth0 tunl0; do sudo bash -c "echo 0 > /proc/sys/net/ipv4/conf/${if}/rp_filter"; done
```

I still can't ping `192.168.1.1` from node2

**Comment by Symmetric** [comment]
@mzupan / @arjanschaaf , might be faster to debug on slack; feel free to jump on and ping me at calicousers.slack.com. (My username there is paul.tiplady).

@mzupan, your rules don't look right -- from my instructions, <nodes subnet> is the subnet containing your nodes' main interfaces (i.e. the underlay). This must not overlap with the pool subnet range. You've used the pool CIDR.

So for example if node1 has eth0 IP 10.245.1.1/24, and cbr0 IP 192.168.1.1/24, your rules would be:

```
echo '8    docker' >> /etc/iproute2/rt_tables
 ip rule add from 192.168.1.1/24 table docker
 ip route add 10.245.0.0/24 table docker dev tunl0
```

Can you try replacing the rules and let me know if that works?

**Comment by mzupan** [comment]
@Symmetric ok looks like i mis-understood the `docker dev tunl0` route cidr and with the correct one.. I'm now able to ping containers outside the same host

**Comment by arjanschaaf** [comment]
I got the basic setup also working with some great support by @Symmetric on slack!
