### ISSUE TITLE
Plugin logs do not wrap

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico-kubernetes#66]
The plugin generates log output to `/var/log/calico/kubernetes/calico.log` but this log doesn't have any log wrapping which can lead to giant logfiles.

We should follow the example of the other Calico component logs, and put plugin logs in their own directory.

For example,
`/var/log/calico/kubernetes/exec-plugin/current.log`

**Comment by Symmetric** [comment]
The cheapo fix is to just use a [RotatingFileHandler](https://docs.python.org/2/library/logging.handlers.html#rotatingfilehandler) logger, rather than a FileHandler.

**Comment by alexhersh** [comment]
Used the builtin rotating file handler instead of the `svlogd` process. Logs fill at 10M and 5 rotations are saved.
