### ISSUE TITLE
Logs are impossible to follow in parallel execution

### ISSUE THREAD

**Issue by Symmetric** [projectcalico/calico-kubernetes#72]
Kubelet runs pod updates concurrently, so we see logs from multiple plugin invocations interleaved. It's impossible to tell which log comes from which invocation.

We should prefix each log with a correlator, probably the 12-char concatenated docker ID.

We should be able to bake this into the log command and formatter so it doesn't need to be explicitly passed to every log statement.

**Comment by alexhersh** [comment]
I'll look into this as I fix #66

**Comment by Symmetric** [comment]
Fine; let’s keep the implementations as separate PRs though (easier to review).

**Comment by alexhersh** [comment]
I have a working branch [here](https://github.com/alexhersh/calico-kubernetes/tree/logID)which produces the following output
```
2015-10-14 20:59:20,247 20379 calico.ca5ac11d04a1 INFO Adding tag kube-system_kubernetes.io_cluster-service_true
2015-10-14 20:59:20,251 20377 calico.510a7e7f7286 INFO Finished configuring profile.
2015-10-14 20:59:20,252 20377 calico.510a7e7f7286 INFO Calico network plugin execution complete
2015-10-14 20:59:20,254 20379 calico.ca5ac11d04a1 INFO Finished applying tags.
```
I havent created a PR yet because its got some dependencies on other PRs

**Comment by Symmetric** [comment]
Not sure where the 'calico.' is coming from; can you remove that? It's a drag to have so many redundant characters in every log.

**Comment by alexhersh** [comment]
We log some stuff before we pull the docker_id, so I just create a child logger when we find the docker_id. I supposed it isn't unreasonable to just create a new logger instead,

**Comment by Symmetric** [comment]
Ah, now I see what you're doing. I don't think that's the way to go -- use [LoggerAdapter](https://docs.python.org/2/library/logging.html#logging.LoggerAdapter) instead. You can extend the format to include `"%(docker_id)"`, and then wrap the logger with an adapter to pass `(extra={docker_id: "xxx"})`.

That way, you preserve the parent/child hierarchy, which specifies the tree onto which log handlers can be attached.

**Comment by L-MA** [comment]
@Symmetric Don't we currently have something in place to solve this issue? We are currently printing the PID for each running plugin in the logs. If you look at the printout @alexhersh posted you can see the PIDs as `20379` and `20377`.

```
2015-10-14 20:59:20,247 20379 calico.ca5ac11d04a1 INFO Adding tag kube-system_kubernetes.io_cluster-service_true
2015-10-14 20:59:20,251 20377 calico.510a7e7f7286 INFO Finished configuring profile.
2015-10-14 20:59:20,252 20377 calico.510a7e7f7286 INFO Calico network plugin execution complete
2015-10-14 20:59:20,254 20379 calico.ca5ac11d04a1 INFO Finished applying tags.
```

**Comment by Symmetric** [comment]
The pid doesn't tell you which container the log is about; though you could use the pid to find the initial log which stores the docker ID, that's a pain to do in practice.
