### ISSUE TITLE
No way to tell version of plugin that is installed

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico-kubernetes#78]
It would be convenient from a debugging standpoint to have a way to determine which plugin binary is being used (either via logging, or a command like "calico_kubernetes version" which displays the version.

We'd have to be careful to always pin the version in release binaries.

**Comment by Symmetric** [comment]
This should be pretty easy to keep in sync if we use [bumpversion](https://github.com/peritus/bumpversion) or similar.

**Comment by alexhersh** [comment]
Primitive implementation in #122
