### ISSUE TITLE
Kubelet is not being informed of IP address updates

### ISSUE THREAD

**Issue by L-MA** [projectcalico/calico-kubernetes#79]
Logging is currently being streamed to stdout. This causes the Kubernetes status hook to fail since Kubernetes looks to stdout for status hook results. I.e.
```
Oct 20 00:30:43 kube-node1 kubelet[942]: E1020 00:30:43.193752     942 manager.go:343] NetworkPlugin calico failed on the status hook for pod 'no-access' - invalid character '-' after top-level value
```
Therefore, Kubernetes fails to learn about the IP address that Calico assigns to a pod.

**Comment by caseydavenport** [comment]
Note this only applies when using CALICO_IPAM=true.  Fixed in v0.4.0

**Comment by Symmetric** [comment]
Have you actually observed this to cause a failure? My reading of the code is that this error is benign (and in the past, when we didn't explicitly support the status hook, it was so):

```go
		if containerName == PodInfraContainerName {
			if inspectResult.NetworkSettings != nil {
				result.ip = inspectResult.NetworkSettings.IPAddress
			}
			// override the above if a network plugin exists
			if dm.networkPlugin.Name() != network.DefaultPluginName {
				netStatus, err := dm.networkPlugin.Status(pod.Namespace, pod.Name, kubeletTypes.DockerID(dockerID))
				if err != nil {
					glog.Errorf("NetworkPlugin %s failed on the status hook for pod '%s' - %v", dm.networkPlugin.Name(), pod.Name, err)
				} else if netStatus != nil {
					result.ip = netStatus.IP.String()
				}
			}
		}
```

**Comment by caseydavenport** [comment]
Yes - this is an error when we are using CALICO_IPAM=true, since Calico assigns an IP address which is not the one assigned by Docker.

Kubernetes will assume we used the Docker IP address which means at least:
1) The Kubernetes API will report the wrong IP.
2) The kube-proxy will install incorrect proxying rules for services.

**Comment by Symmetric** [comment]
Gotcha, thanks.
