### ISSUE TITLE
Move plugin configuration into etcd

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico-kubernetes#93]
Moving configuration into etcd will simplify plugin deployment, and prevent misconfigurations where one instance of the plugin is configured separately from another instance of the plugin.

We can still use environment variables for override on configuration options where it makes sense.

**Comment by Symmetric** [comment]
This would come in handy for a case I just hit -- in the Vagrant install, we can't easily get at the ENV of the kubelet process.

That said, it does add operational complexity (harder for users to grok what's going on, and make changes when debugging). Might be worth looking in etcd by default, with local environment variables as a hard override?

**Comment by caseydavenport** [comment]
Yep - we'd still need a way of pointing the plugin at `etcd`, but a sensible default would work for the vagrant install case.

We'd probably want to add support to `calicoctl` for configuring this stuff to make it as easy as possible.

**Comment by caseydavenport** [comment]
@Symmetric how about something like this:

- Stop using environment variables for config - instead, move config into an on-disk configuration file combined with etcd.  
- An on-disk configuration file in the same directory as the plugin will be used to bootstrap the plugin, providing the ETCD_AUTHORITY (and any other etcd config - certs, etc).
- All other configuration will be stored in etcd, and will be read by the plugin. 
- Initially, move the following config into `etcd`:
  - KUBE_API_ROOT -> /calico/kubernetes/v1/config/kube-api-root
  - CALICO_IPAM -> /calico/kubernetes/v1/config/calico-ipam
  - KUBE_AUTH_TOKEN -> /calico/kubernetes/v1/config/kube-auth-token
  - DEFAULT_POLICY -> /calico/kubernetes/v1/config/default-policy
  - CALICO_POLICY -> /calico/kubernetes/v1/config/calico-policy
  - LOG_LEVEL -> /calico/kubernetes/v1/config/log-level
- Any of the above configuration settings can be overridden using the on-disk configuration file - this allows the user to make changes on a per-node basis if needed (e.g increase the logging level on a single node).

**Comment by Symmetric** [comment]
General approach sounds good to me. If we keep the ETCD_AUTHORITY env variable, then our current guides wouldn't need a rewrite though? 

I don't necessarily mind allowing these to be configured in the env _as well_ as by file (with ENV > file > etcd)

**Comment by caseydavenport** [comment]
#94 addresses reading config from a file.  Using `etcd` will be a separate PR.

**Comment by caseydavenport** [comment]
Closing since file config is sufficient, and migrating to CNI plugin uses the CNI network configuration file.
